Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
  end
  config.vm.define "cka01" do |server|
    server.vm.hostname="cka01"
    server.vm.network "private_network", ip: "172.28.128.51"
  end
  config.vm.define "cka02" do |server|
    server.vm.hostname="cka02"
    server.vm.network "private_network", ip: "172.28.128.52"
  end
  config.vm.define "cka03" do |server|
    server.vm.hostname="cka03"
    server.vm.network "private_network", ip: "172.28.128.53"
  end
end