apiVersion: v1
kind: Service
metadata:
  name: wp-mysql
spec:
  ports:
  - port: 3306
  selector:
    app: wp-mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-mysql
spec:
  selector:
    matchLabels:
      app: wp-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wp-mysql
    spec:
      containers:
      - name: mysql
        image: registry.cn-zhangjiakou.aliyuncs.com/breezey/mysql:5.7
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: pass123
        - name: MYSQL_DATABASE
          value: wp
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
