apiVersion: v1
kind: Pod
metadata:
  name: the-first-nginx-pod
  labels:
    run: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.21
    resources:
      requests:
        cpu: "0.1"
        memory: 32Mi
      limits:
        cpu: "200m"
        memory: 64Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always