apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-first-nginx-deploy
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        resources:
          requests:
            cpu: "0.1"
            memory: 32Mi
          limits:
            cpu: "200m"
            memory: 64Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always